
-- Sequências criadas para ter autoincremento nos triggers.
CREATE SEQUENCE GEN_TABELA_PRODUTO_CODIGO;

CREATE SEQUENCE GEN_TABELA_CLIENTE_CODIGO;

CREATE SEQUENCE GEN_TABELA_VENDAS_NUMERO;

-- Domínios
CREATE DOMAIN DM_BOOLEAN AS CHAR(1)
CHECK (VALUE IN ('S', 'N'));

CREATE DOMAIN DM_CODIGO AS INTEGER
CHECK (VALUE >= 0);

-- Criação das tabelas
CREATE TABLE TABELA_PRODUTO (
    CODIGO DM_CODIGO PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO_CUSTO NUMERIC(10,2),
    PRECO_VENDA NUMERIC(10,2),
    ESTOQUE INTEGER,
    CATEGORIA VARCHAR(50),
    DATA_CADASTRO DATE DEFAULT CURRENT_DATE,
    ATIVO DM_BOOLEAN DEFAULT 'S'
);

CREATE TABLE TABELA_CLIENTE( 
    CODIGO DM_CODIGO PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF_CNPJ VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR(100),
    DATA_CADASTRO DATE DEFAULT CURRENT_DATE,
    ATIVO DM_BOOLEAN DEFAULT 'S'
);

CREATE TABLE TABELA_VENDAS ( 
    NUMERO DM_CODIGO, 
    DATA_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENTE_CODIGO DM_CODIGO,  
    VALOR_TOTAL NUMERIC(10,2),
    PRIMARY KEY (NUMERO, DATA_VENDA), 
    FOREIGN KEY(CLIENTE_CODIGO) REFERENCES TABELA_CLIENTE(CODIGO) 
);

CREATE TABLE TABELA_ITEM_VENDA(
    VENDA_NUMERO DM_CODIGO,
    VENDA_DATA TIMESTAMP,
    PRODUTO_CODIGO DM_CODIGO,
    QUANTIDADE INTEGER,
    PRECO_UNITARIO NUMERIC(10,2),
    PRIMARY KEY (VENDA_NUMERO, VENDA_DATA, PRODUTO_CODIGO),
    FOREIGN KEY (VENDA_NUMERO, VENDA_DATA) REFERENCES TABELA_VENDAS(NUMERO, DATA_VENDA),
    FOREIGN KEY (PRODUTO_CODIGO) REFERENCES TABELA_PRODUTO(CODIGO)
);

-- Criando as sequências para autoincremento nos triggers
CREATE SEQUENCE GEN_TABELA_PRODUTO_CODIGO;
CREATE SEQUENCE GEN_TABELA_CLIENTE_CODIGO;
CREATE SEQUENCE GEN_TABELA_VENDAS_NUMERO;


SET TERM ^^ ;
-- Trigger para a tabela de produtos
CREATE TRIGGER TRG_BI_TABELA_PRODUTO FOR TABELA_PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS 
BEGIN
    IF (NEW.CODIGO IS NULL) THEN 
        NEW.CODIGO = NEXT VALUE FOR GEN_TABELA_PRODUTO_CODIGO;
END ^^ 

-- Trigger para a tabela de clientes
CREATE TRIGGER TRG_BI_TABELA_CLIENTE FOR TABELA_CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS 
BEGIN
    IF (NEW.CODIGO IS NULL) THEN 
        NEW.CODIGO = NEXT VALUE FOR GEN_TABELA_CLIENTE_CODIGO;
END ^^

-- Trigger para a tabela de vendas
CREATE TRIGGER TRG_BI_TABELA_VENDAS FOR TABELA_VENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.NUMERO IS NULL) THEN 
        NEW.NUMERO = NEXT VALUE FOR GEN_TABELA_VENDAS_NUMERO;
END ^^

SET TERM ; ^^ 
