CREATE TABLE TABELA_PRODUTO (
    CODIGO DM_CODIGO PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO_CUSTO NUMERIC(10,2),
    PRECO_VENDA NUMERIC(10,2),
    ESTOQUE INTEGER,
    CATEGORIA VARCHAR(50),
    DATA_CADASTRO DATE DEFAULT CURRENT_DATE,
    ATIVO DM_BOOLEAN DEFAULT 'S'
);

CREATE TABLE TABELA_CLIENTE( 
    CODIGO DM_CODIGO PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF_CNPJ VARCHAR(14) UNIQUE,
    DATA_NASCIMENTO DATE,
    EMAIL VARCHAR(100),
    DATA_CADASTRO DATE DEFAULT CURRENT_DATE,
    ATIVO DM_BOOLEAN DEFAULT 'S'
);

CREATE TABLE TABELA_VENDAS ( 
    NUMERO DM_CODIGO, 
    DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENTE_CODIGO DM_CODIGO, 
    VALOR_TOTAL NUMERIC(10,2),
    PRIMARY KEY (NUMERO, DATA_VENDA), 
    FOREIGN KEY(CLIENTE_CODIGO) REFERENCES TABELA_CLIENTE(CODIGO) 
);

CREATE TABLE TABELA_ITEM_VENDA(
    VENDA_NUMERO DM_CODIGO,
    VENDA_DATA TIMESTAMP,
    PRODUTO_CODIGO DM_CODIGO,
    QUANTIDADE INTEGER,
    PRECO_UNITARIO NUMERIC(10,2),
    PRIMARY KEY (VENDA_NUMERO, VENDA_DATA, PRODUTO_CODIGO),
    FOREIGN KEY (VENDA_NUMERO, VENDA_DATA) REFERENCES TABELA_VENDAS(NUMERO, DATA_VENDA),
    FOREIGN KEY (PRODUTO_CODIGO) REFERENCES TABELA_PRODUTO(CODIGO)
);